variables:
  REGISTRY: quay.io
  REGISTRY_AUTHOR: ukhomeofficedigital
  REGISTRY_EMAIL: gitlab@digital.homeoffice.gov.uk
  REGISTRY_USER: ukhomeofficedigital+gitlab
  NAME: hod-vault

stages:
- build
- deploy

build:
  stage: build
  script:
    - docker build -t homeoffice.io/${NAME}:${CI_BUILD_ID} .
    - docker rmi homeoffice.io/${NAME}:${CI_BUILD_ID}

deploy:
  stage: deploy
  script:
    - export VERSION=$CI_BUILD_TAG
    - '[[ "$VERSION" == "master" ]] && VERSION="latest"'
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN} -e ${REGISTRY_EMAIL} ${REGISTRY}
    - docker build -t ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION} .
    - docker push ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION}
    - docker rmi ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION}
  only:
    - /^master$/
    - /^v([0-9]{1,3}[.]?){3}.*$/
